#include "qm.h"
#include "qm_log.h"
#include "httpd.h"
#include "httpd_priv.h"
#include "qm_wifi.h"
#include "qm_work.h"
#include "qm_event.h"

#define EXAMPLE_WIFI_SSID       "xjiang"
#define EXAMPLE_WIFI_PASSWORD   "xjwl2015"

#define EXAMPLE_WIFI_AP_SSID       "wells"
#define EXAMPLE_WIFI_AP_PASSWORD   "1234567890"
#define EXAMPLE_MAX_STA_CONN    5

static qm_task_t web_task = {0};

#define LOG_TAG "web server"

/*
** This is a static page of HTML.  It is loaded into the content
** tree using httpdAddStaticContent( ).
*/
#define test1_html "<HTML><BODY>This is just a test</BODY>"

#define ember_code1 "printf(\"This is from ember in process %d\n\",getpid());"
#define ember_code "load \"/usr/local/nk/www/content.lib\"; dispatchWebPage(\"/index.html\");"

/*
** Below are 2 dynamic pages, each generated by a C function.  The first
** is a simple page that offers a little dynamic info (the process ID)
** and the setups up a test link and a simple form.
** 
** The second page processes the form.  As you can see, you can access
** the form data from within your C code by accessing the symbol table
** using httpdGetVariableByName() (and other similar functions).  You
** can also include variables in the string passed to httpdOutput( ) and
** they will be expanded automatically.
*/
void index_html(
	httpd	*server,
	httpReq	*request)
{

	httpdPrintf(server, request,
	    "Click <A HREF=/test1.html>here</A> to view a test page<P>\n");
	httpdPrintf(server, request,
	    "Click <A HREF=/login.html>here</A> to authenticate<P>\n");
	httpdPrintf(server, request,
	    "Or <A HREF=/wildcard/foo>here</A> for a test wildcard page<P>\n");
	httpdPrintf(server, request,
	    "<P><FORM ACTION=test2.html METHOD=POST>\n");
	httpdPrintf(server, request,
	    "Enter your name <INPUT NAME=name SIZE=10>\n");
	httpdPrintf(server, request,
	    "<INPUT TYPE=SUBMIT VALUE=Click!><P></FORM>\n");
	
	return;
}

void test2_html(
	httpd	*server,
	httpReq	*request)
{
	httpVar	*variable;

	/*
	** Grab the symbol table entry to see if the variable exists
	*/
	variable = httpdGetVariableByName(server, request, "name");
	if (variable == NULL)
	{
		httpdPrintf(server,request,"Missing form data!");
		return;
	}

	/*
	** Use httpdOutput() rather than httpdPrintf() so that the variable
	** embedded in the text is expanded automatically
	*/
	httpdOutput(server, request, "Hello ${name}");
}

void test3_html(
	httpd	*server,
	httpReq	*request)
{
	char	*path;

	path = httpdRequestPath(request);
	httpdOutput(server,request,"Wilcard dynamic request received<P>");
	httpdPrintf(server,request,"The requested path was %s<P>", path);
}


void login_html(
	httpd	*server,
	httpReq	*request)
{
	if (httpdAuthenticate(server, request, "LibHTTPD Test") == 0)
		return;
	httpdPrintf(server, request, "Your username is '%s'<P>\n",
		request->authUser);
	httpdPrintf(server, request, "Your password is '%s'<P>\n",
 		request->authPassword);
	httpdOutput(server, request,
		"Click <A HREF=login2.html>here</A> to force reauthentication");
	httpdOutput(server, request,
		".  Use a username = test password = 123");
}



void login2_html(
	httpd	*server,
	httpReq	*request)
{
	if (httpdAuthenticate(server, request, "LibHTTPD Test") == 0)
	{
		httpdOutput(server, request, "Authentication failure(1).");
		return;
	}
	if (strcmp(request->authUser, "test") != 0 ||
	    strcmp(request->authPassword, "123") != 0)
	{
		httpdForceAuthenticate(server, request, "LibHTTPD Test");
		httpdOutput(server, request, "Authentication failure (2).");
		return;
	}
	httpdOutput(server, request, "Your login was accepted.");
}

void myError404Handler(
	httpd	*server,
	httpReq	*request,
	int	error)
{
	httpdOutput(server, request,
	    "Whoa there.  You hit a page that doesn't exist! <P><BR><BR>\n");
	httpdOutput(server, request,
	    "Or in other words : <B>Error 404</B>\n\n");
}

void cfg_get(
	httpd	*server,
	httpReq	*request)
{
   
   QM_LOGD(LOG_TAG, "%s", request->readBuf);
   httpdSetContentType(server, request,"application/json");
   httpdOutput(server, request,"{\"deviceId\":\"sxcsa5d444455\"}");
}

void web_server_task(void *arg)
{
    int result;
    httpd	*server;
	httpReq	*request;

    /*
	** Create a server and setup our logging
	*/
	server = httpdCreate(NULL, 80);
	if (server == NULL){
		QM_LOGE(LOG_TAG, "Can't create web server");
	}
	httpdSetAccessLog(server, stdout);
	httpdSetErrorLog(server, stdout);

	/*
	** We are fussy and don't want the default Error 404 page
	*/
	httpdSetErrorFunction(server,404, myError404Handler);

	/*
	** Setup some content for the server
	*/
	httpdAddCContent(server,"/", "form.html", HTTP_TRUE, 
		NULL, index_html);
	httpdAddCContent(server,"/", "test2.html", HTTP_FALSE, 
		NULL, test2_html);
	httpdAddCContent(server,"/", "login.html", HTTP_FALSE,
		NULL, login_html);
	httpdAddCContent(server,"/", "login2.html", HTTP_FALSE,
		NULL, login2_html);
	httpdAddCWildcardContent(server,"/wildcard", NULL, test3_html);
	httpdAddStaticContent(server, "/", "test1.html", HTTP_FALSE,
		NULL, test1_html);

	httpdAddCContent(server,"/cfg/", "get", HTTP_FALSE, 
		NULL, cfg_get);

	/*
	** Go into our service loop
	*/

    while(1){

		request = httpdReadRequest(server, 5000, &result);
		if (request == NULL && result == 0)
		{
			QM_LOGD(LOG_TAG, "web server wait timeout ... \n");
			continue;
		}
		if (result < 0)
		{
			QM_LOGE(LOG_TAG, "Error ... \n");
			continue;
		}
		
		httpdProcessRequest(server, request);
		httpdEndRequest(server, request);
	}

	httpdDestroy(server);
	qm_task_exit(&web_task);
}

static void qm_event_handler(qm_input_event_t *input_event, void *arg)
{
    qm_wifi_event_info_t *event_info = (qm_wifi_event_info_t*)input_event->value;

    switch(input_event->sub_event){

        case QM_WIFI_EVENT_STA_START:
            QM_LOGD(LOG_TAG, "connect to the AP");
            qm_wifi_connect();
        break;

        case QM_WIFI_EVENT_STA_STOP:

        break;

        case QM_WIFI_EVENT_STA_CONNECTED:
            QM_LOGD(LOG_TAG, "connected to the AP");
        break;

        case QM_WIFI_EVENT_STA_GOT_IP:
            QM_LOGD(LOG_TAG, "sta got ip");

            QM_LOGD(LOG_TAG, "ip:"      QM_IPSTR, QM_IP2STR(&event_info->got_ip.ip_info.ip));
            QM_LOGD(LOG_TAG, "netmask:" QM_IPSTR, QM_IP2STR(&event_info->got_ip.ip_info.netmask));
            QM_LOGD(LOG_TAG, "gw:"      QM_IPSTR, QM_IP2STR(&event_info->got_ip.ip_info.gw));

        break;

        case QM_WIFI_EVENT_STA_LOST_IP:

        break;

        case QM_WIFI_EVENT_STA_DISCONNECTED:

                QM_LOGD(LOG_TAG, "sta disconnected reason: %d", event_info->sta_disconnected.reason);
                qm_wifi_connect();
                QM_LOGD(LOG_TAG, "retry to connect to the AP");

        break;

        case QM_WIFI_EVENT_AP_START:

            QM_LOGD(LOG_TAG, "AP Start");
        break;

        case QM_WIFI_EVENT_AP_STOP:

        break;

        case QM_WIFI_EVENT_AP_STACONNECTED:
            QM_LOGD(LOG_TAG, "station join "QM_MACSTR" ", QM_MAC2STR(event_info->ap_staconnected.mac));

        break;

        case QM_WIFI_EVENT_AP_STAIPASSIGNED:
            QM_LOGD(LOG_TAG, "station ip:" QM_IPSTR, QM_IP2STR(&event_info->ap_staipassigned.ip));

        break;

        case QM_WIFI_EVENT_AP_STADISCONNECTED:
            QM_LOGD(LOG_TAG, "station leave "QM_MACSTR" ", QM_MAC2STR(event_info->ap_stadisconnected.mac));

        break;


        default:
        break;
    }
}

void qm_application_start(void)
{
	qm_err_t ret = QM_EOK;

    qm_wifi_config_t sta_config = {
        .sta = {
            .ssid = EXAMPLE_WIFI_SSID,
            .ssid_len = strlen(EXAMPLE_WIFI_SSID),
            .password = EXAMPLE_WIFI_PASSWORD,
            .password_len = strlen(EXAMPLE_WIFI_PASSWORD),
        },
    };

    qm_wifi_config_t ap_config = {
        .ap = {
            .ssid = EXAMPLE_WIFI_AP_SSID,
            .ssid_len = strlen(EXAMPLE_WIFI_AP_SSID),
            .password = EXAMPLE_WIFI_AP_PASSWORD,
            .password_len = strlen(EXAMPLE_WIFI_AP_PASSWORD),
            .max_connection = EXAMPLE_MAX_STA_CONN,
            .authmode = QM_WIFI_AUTH_WPA_WPA2_PSK,
        },
    };

    qm_event_register(QM_EVENT_WIFI, qm_event_handler, NULL);

    qm_wifi_init();

    qm_wifi_set_mode(QM_WIFI_MODE_APSTA);

    qm_wifi_set_config(QM_WIFI_IF_AP, &ap_config);
    qm_wifi_set_config(QM_WIFI_IF_STA, &sta_config);

    qm_wifi_start();

    qm_task_new(&web_task, "web server", web_server_task, NULL, 8*1024, 20);
}